version: '{branch}.{build}'
image: Visual Studio 2019
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore "Source\Domain.sln"
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
configuration: Release
deploy:
- provider: NuGet
  api_key:
    secure: rD2gGQmfm43pax0DCOHZ0GoM6/+JzRmp6FNNDPHEC/0qjDUS48pU+r9rjK8T08wf
  on:
    APPVEYOR_REPO_TAG: true
