using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Affecto.Patterns.Domain
{
    /// <summary>
    /// Base class for implementing asynchronous domain repositories for aggregate root types.
    /// </summary>
    /// <typeparam name="TAggregate">The type of the aggregate root.</typeparam>
    public abstract class AsyncDomainRepositoryBase<TAggregate> : IAsyncDomainRepository<TAggregate>
        where TAggregate : AggregateRoot
    {
        protected readonly DomainEventBrokerBase domainEventBroker;

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainRepositoryBase{TAggregate}"/> class.
        /// </summary>
        /// <param name="domainEventBroker">A broker used for publishing domain events generated by aggregate roots.</param>
        protected AsyncDomainRepositoryBase(DomainEventBrokerBase domainEventBroker)
        {
            this.domainEventBroker = domainEventBroker ?? throw new ArgumentNullException(nameof(domainEventBroker));
        }

        /// <summary>
        /// Asynchronously executes all events that have been applied to the given aggregate root instance.
        /// </summary>
        /// <param name="aggregateRoot">The changed aggregate root instance.</param>
        public virtual async Task ApplyChangesAsync(TAggregate aggregateRoot)
        {
            if (aggregateRoot == null)
            {
                throw new ArgumentNullException(nameof(aggregateRoot));
            }

            await PublishPendingEventsAsync(aggregateRoot.GetPendingEvents(), domainEventBroker).ConfigureAwait(false);
        }

        /// <summary>
        /// Asynchronously executes all events that have been applied to the given set of aggregate root instances.
        /// </summary>
        /// <param name="aggregateRoots">The changed aggregate root instances.</param>
        public virtual async Task ApplyChangesAsync(IReadOnlyCollection<TAggregate> aggregateRoots)
        {
            if (aggregateRoots == null)
            {
                throw new ArgumentNullException(nameof(aggregateRoots));
            }

            if (aggregateRoots.Any(a => a == null))
            {
                throw new ArgumentNullException(nameof(aggregateRoots), "Aggregate root list cannot contain null values.");
            }

            foreach (TAggregate aggregateRoot in aggregateRoots)
            {
                await PublishPendingEventsAsync(aggregateRoot.GetPendingEvents(), domainEventBroker).ConfigureAwait(false);
            }
        }

        /// <summary>
        /// Asynchronously finds an aggregate root instance from the repository using its id.
        /// </summary>
        /// <param name="id">Aggregate root instance id.</param>
        /// <returns>Aggregate root instance.</returns>
        public abstract Task<TAggregate> FindAsync(Guid id);

        /// <summary>
        /// Asynchronously executes all events that have been applied to the given aggregate root instance.
        /// </summary>
        /// <param name="pendingEvents">A list of events pending for publishing.</param>
        /// <param name="eventBroker">The event broker to be used for publishing events.</param>
        protected static async Task PublishPendingEventsAsync(IEnumerable<IDomainEvent> pendingEvents, DomainEventBrokerBase eventBroker)
        {
            await eventBroker.PublishEventsAsync(pendingEvents).ConfigureAwait(false);
        }
    }
}