using System;
using System.Collections.Generic;
using System.Linq;

namespace Affecto.Patterns.Domain
{
    /// <summary>
    /// Base class for implementing domain repositories for aggregate root types.
    /// </summary>
    /// <typeparam name="TAggregate">The type of the aggregate root.</typeparam>
    public abstract class DomainRepositoryBase<TAggregate> : IDomainRepository<TAggregate>
        where TAggregate : AggregateRoot
    {
        protected readonly DomainEventBrokerBase domainEventBroker;

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainRepositoryBase{TAggregate}"/> class.
        /// </summary>
        /// <param name="domainEventBroker">A broker used for publishing domain events generated by aggregate roots.</param>
        protected DomainRepositoryBase(DomainEventBrokerBase domainEventBroker)
        {
            this.domainEventBroker = domainEventBroker ?? throw new ArgumentNullException(nameof(domainEventBroker));
        }

        /// <summary>
        /// Executes all events that have been applied to the given aggregate root instance.
        /// </summary>
        /// <param name="aggregateRoot">The changed aggregate root instance.</param>
        public virtual void ApplyChanges(TAggregate aggregateRoot)
        {
            if (aggregateRoot == null)
            {
                throw new ArgumentNullException(nameof(aggregateRoot));
            }

            PublishPendingEvents(aggregateRoot.GetPendingEvents(), domainEventBroker);
        }

        /// <summary>
        /// Executes all events that have been applied to the given set of aggregate root instances.
        /// </summary>
        /// <param name="aggregateRoots">The changed aggregate root instances.</param>
        public virtual void ApplyChanges(IReadOnlyCollection<TAggregate> aggregateRoots)
        {
            if (aggregateRoots == null)
            {
                throw new ArgumentNullException(nameof(aggregateRoots));
            }

            if (aggregateRoots.Any(a => a == null))
            {
                throw new ArgumentNullException(nameof(aggregateRoots), "Aggregate root list cannot contain null values.");
            }

            foreach (TAggregate aggregateRoot in aggregateRoots)
            {
                PublishPendingEvents(aggregateRoot.GetPendingEvents(), domainEventBroker);
            }
        }

        /// <summary>
        /// Finds an aggregate root instance from the repository using its id.
        /// </summary>
        /// <param name="id">Aggregate root instance id.</param>
        /// <returns>Aggregate root instance.</returns>
        public abstract TAggregate Find(Guid id);

        /// <summary>
        /// Publishes all events that have been applied to the given aggregate root instance.
        /// </summary>
        /// <param name="pendingEvents">A list of events pending for publishing.</param>
        /// <param name="eventBroker">The event broker to be used for publishing events.</param>
        protected static void PublishPendingEvents(IEnumerable<IDomainEvent> pendingEvents, DomainEventBrokerBase eventBroker)
        {
            eventBroker.PublishEvents(pendingEvents);
        }
    }
}